services:
  - type: web
    name: frontend-service
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    repo: https://github.com/s-vashistha/SNB
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: 'http://localhost:10000/api/data'

  - type: web
    name: backend-service
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    repo: https://github.com/s-vashistha/SNB
    branch: main
    envVars:
      - key: DB_HOST
        value: dpg-crf8pstsvqrc73f5c770-a
      - key: DB_USER
        value: snbpostdata_user
      - key: DB_PASSWORD
        value: m64gJ3y7LlYgIXUPV5syQA6OKAR7gXVi
      - key: NODE_ENV
        value: production
