services:
  - type: web
    name: frontend-service
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    repo: https://github.com/s-vashistha/SNB
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://snb-1.onrender.com
    autoDeploy: true  

  - type: web
    name: backend-service
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    repo: https://github.com/s-vashistha/SNB
    branch: main
    envVars:
      - key: DB_HOST
        value: dpg-crf8pstsvqrc73f5c770-a
      - key: DB_USER
        value: snbpostdata_user
      - key: DB_PASSWORD
        value: m64gJ3y7LlYgIXUPV5syQA6OKAR7gXVi
      - key: DB_PORT
        value: '5432'
      - key: DB_NAME
        value: snbpostdata
      - key: DATABASE_URL
        value: postgresql://snbpostdata_user:m64gJ3y7LlYgIXUPV5syQA6OKAR7gXVi@dpg-crf8pstsvqrc73f5c770-a/snbpostdata
      - key: NODE_ENV
        value: production
    autoDeploy: true  